version: '2'

services:
  # https://github.com/docker/compose/issues/3412#issuecomment-549808961
  nginx:
    hostname: nginx
    domainname: nginx.local
    image: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      net:
        aliases:
          - nginx

  web:
    hostname: web
    domainname: web.local
    image: nginx
    ports:
      - "3000:80"
    networks:
      net:
        aliases:
          - web
networks:
 net: