apiVersion: v1
kind: Service
metadata:
  namespace: "pihole"
  name: unbound-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: dns
  clusterIP: "10.43.1.1"
  ports:
    - protocol: UDP
      port: 53
      targetPort: 5053
