apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "pihole"
  name: unbound-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: dns
  template:
    metadata:
      labels:
        component: dns
    spec:
      containers:
        - name: unbound
          image: klutchell/unbound
          ports:
            - containerPort: 5053
              protocol: UDP