version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
  ngrok:
    # image: wernight/ngrok
    build:
      dockerfile: Dockerfile
      args:
        AUTH_TOKEN: $AUTH_TOKEN
      context: .
    links:
      - web
    ports:
      - "4551:4551"
    env_file: .env
    environment:
      # NGROK_PORT: web:80
      DOMAIN: web
      PORT: "80"
